### PR TITLE
Add Alpha Prime support

### PR DESCRIPTION
**Pull request by flopie2009**
This PR inserts the support for the Alpha Prime which config is already included within the repository.

### CODE REVIEW

**Comment by flopie2009** [comment]
@valgur: is it possible to add the Alpha Prime support and to create a new release?

**Comment by valgur** [comment]
Thanks for the PR, I'll try to get this merged asap.

I have so far not really tested the decoder with either VLS-128 or Alpha Prime data, though, and I'd like to do that before merging and releasing these changes. I'll see if I can find anything online. If you know of any or can share a small sample, it would help a lot and would be much appreciated.

**Comment by valgur** [comment]
I failed to find any VLS-128 or Alpha Prime data online, neither as PCAP or a rosbag. So, if you can share even a single scan's worth of sample data it would help a lot. I would probably add a unit test based on it.

**Comment by flopie2009** [comment]
Sorry for the late reply. Actually, I did not found any public VLS-128 or Alpha Prime data as well. Unfortunately, I can not share the data that I am working on, but I can assure you that the Alpha Prime is running based on this branch. Otherwise, I would not have set up this branch. The only thing that I could not tested yet is the accuracy of the timestamps. But this will be tested soon.
So how would you like to proceed?

**Comment by valgur** [comment]
Ok, that's understandable, and I'm content with merging this based on your assurance alone that it works. It's an improvement over the status quo of zero testing for this model after all. Thanks again.

**Pull request merged**
